---
build_from:
  aarch64: ghcr.io/hassio-addons/adguard/aarch64:4.8.17
  amd64: ghcr.io/hassio-addons/adguard/amd64:4.8.17
  armv7: ghcr.io/hassio-addons/adguard/armv7:4.8.17
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
